DROP TABLE N_ROLLCALL;
DROP TABLE O_ROLLCALL;
CREATE TABLE N_ROLLCALL(ROLL INT PRIMARY KEY NOT NULL, SNAME VARCHAR(30), EMAIL VARCHAR(30));
CREATE TABLE O_ROLLCALL(ROLL INT PRIMARY KEY NOT NULL, SNAME VARCHAR(30), EMAIL VARCHAR(30));

INSERT INTO N_ROLLCALL(ROLL,SNAME,EMAIL) VALUES(1,'Arshad','arshad@gmail.com');
INSERT INTO N_ROLLCALL(ROLL,SNAME,EMAIL) VALUES(2,'Chinmay','chinu@gmail.com');
INSERT INTO N_ROLLCALL(ROLL,SNAME,EMAIL) VALUES(3,'Mansi','mansi@gmail.com');
INSERT INTO N_ROLLCALL(ROLL,SNAME,EMAIL) VALUES(4,'Kesar','kesar@gmail.com');

INSERT INTO O_ROLLCALL(ROLL,SNAME,EMAIL) VALUES(5,'Vedant','ved@gmail.com');
INSERT INTO O_ROLLCALL(ROLL,SNAME,EMAIL) VALUES(6,'Shreyas','tillu@gmail.com');
INSERT INTO O_ROLLCALL(ROLL,SNAME,EMAIL) VALUES(4,'Kesar','kesar@gmail.com');

SELECT * FROM N_ROLLCALL;
SELECT * FROM O_ROLLCALL;

